name: 'Sync Submodules'

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Sync Submodules'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: org/parent_repository
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Git Submodule Update
        run: |
          git pull --recursive-submodules
          git submodule update --remote --recursive

      - name: Commit
        run : |
          git config user.email "bot@noreply.github.com"
          git config user.name "GitHub Actions - submodule update"
          git add --all
          git commit -m "submodule update" || echo "No changes to commit"
          git push
